### ISSUE TITLE
Drop the discover page and the elasticsearch endpoint

### ISSUE THREAD

**Issue by rgbkrk** [Netflix-Skunkworks/commuter#6]
Given that we're going to be surfacing the discovery endpoint in a different way, I think we can take this feature out. This would also include the elasticsearch bits.

* [x] Nuke Discovery Providers
* [x] Nuke `discover.js`
* [x] Remove `Discover` from the nav bar

**Comment by rgbkrk** [comment]
We do get a lot of viewership on our discover page though. 😞

**Comment by stormpython** [comment]
Submitted this [PR](https://stash.corp.netflix.com/projects/DSEPLAT/repos/commuter-nflx/pull-requests/65/overview).

**Comment by rgbkrk** [comment]
All set!
