### ISSUE TITLE
Create a `pages/_error.js` page

### ISSUE THREAD

**Issue by rgbkrk** [Netflix-Skunkworks/commuter#7]
Follow along with [next's custom error handling](https://nextjs.org/docs/#custom-error-handling) and create a `pages/_error.js` page that surfaces errors in a good contextual way.

**Comment by stormpython** [comment]
Opened [PR 74](https://stash.corp.netflix.com/projects/DSEPLAT/repos/commuter-nflx/pull-requests/74/overview)

**Comment by stormpython** [comment]
I am going to go ahead and remove the [WIP] label from this PR. It should use the new error handling and I can make a follow up PR to render something better than it is currently rendering.
