### ISSUE TITLE
Upgrade React

### ISSUE THREAD

**Issue by rgbkrk** [Netflix-Skunkworks/commuter#8]
Likely to be able to handle the nteract component upgrades (#5), we'll need to upgrade React to `16.8.x`. We may or may not have to upgrade next.js for this as well.

**Comment by stormpython** [comment]
Adding a link to merged [PR#76](https://stash.corp.netflix.com/projects/DSEPLAT/repos/commuter-nflx/pull-requests/76/overview) from stash.

@rgbkrk, since the PR has been merged, can we close this issue?

**Comment by rgbkrk** [comment]
Done deal!
